version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/lycle-backend
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 200
      runas: root
