spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lycle_backend?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://lycle-rds.c9qq9ay6jtoe.ap-northeast-2.rds.amazonaws.com:3306/lycle_rds?serverTimezone=Asia/Seoul
    username: root
    password: 9520awdr0259!
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true # DDL 출력
  mail:
    host: smtp.gmail.com
    port: 587
    username: dmswn0261@ajou.ac.kr
    password: okqwxajmtkuzagvu
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
jwt:
  secret: asdfassd
cloud:
  aws:
    credentials:
      access-key: AKIA6FK2JXXYFMVKVYQM
      secret-key: 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
    s3:
      bucket: lycle-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false


